#!/usr/bin/perl 
use warnings;
use strict;
use diagnostics;
use v5.28;
use Data::Dumper;
use File::Find; # use this module

#list all files in current dir..list full path meaning dir and file name
find sub {print "Here's a file: $File::Find::name\n"},'.';

#list all files in current dir..with file name, no dir... '-d' = file test operator for directory (omits dir)
find sub {print "Here's a file: $File::Find::name\n" if !-d},'.';

#list ONLY TEXT files in current dir 
find sub {print "Here's a file: $File::Find::name\n" if -T},'.';


#list all dirs in current dir
find sub {print "Here's a file: $File::Find::dir\n"},'.';


#list all TEXT files ONLY except for a certain dir...e.g. all text files except for 'dir1'
find sub {
  $File::Find::prune = 1 if /dir1/;
  print "Here's a file: $File::Find::name\n" if -T
},
'.';
